MvcCorePersonajesSeries/Models/ErrorViewModel.cs
namespace MvcCorePersonajesSeries.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCorePersonajesSeries/Models/Personaje.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace MvcCorePersonajesSeries.Models
{
    public class Personaje
    {
        [JsonProperty("idPersonaje")]
        public int IdPersonaje { get; set; }
        [JsonProperty("nombre")]
        public string Nombre { get; set; }
        [JsonProperty("imagen")]
        public string Imagen { get; set; }
        [JsonProperty("serie")]
        public string Serie { get; set; }
    }
}

MvcCorePersonajesSeries/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCorePersonajesSeries.Models;
using System.Diagnostics;

namespace MvcCorePersonajesSeries.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCorePersonajesSeries/Controllers/SeriesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCorePersonajesSeries.Models;
using MvcCorePersonajesSeries.Services;

namespace MvcCorePersonajesSeries.Controllers
{
    public class SeriesController : Controller
    {
        private ServicePersonajesSeries service;

        public SeriesController(ServicePersonajesSeries service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Personaje> personajes =
                await this.service.GetAllPersonajes();

            return View(personajes);
        }

        public async Task<IActionResult> Detalles(int id)
        {
            Personaje personaje =
                await this.service.GetPersonajeByIdAsync(id);

            return View(personaje);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Personaje personaje)
        {
            Personaje pers = await this.service.CreatePersonaje(personaje);
            return RedirectToAction("Detalles", new { id = pers.IdPersonaje });
        }
    }
}

MvcCorePersonajesSeries/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCorePersonajesSeries/Views/Series/Create.cshtml
@model MvcCorePersonajesSeries.Models.Personaje

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdPersonaje" class="control-label"></label>
                <input asp-for="IdPersonaje" class="form-control" />
                <span asp-validation-for="IdPersonaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group" id="series">
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@* @section Scripts {
    <script>
        var apiurl = "https://apipersonajesserieswerku.azurewebsites.net/";

        $(document).ready(function () {
            var request = "/api/Series/Series";

            $.ajax({
                url: apiurl + request,
                method: "GET",
                dataType: "json",
                success: function (data) {
                    var html = "";
                    $.each(data, function (index, serie) {
                        html += "<select>";
                        html += "<options value=" + serie + ">" + serie + "</td>";
                        html += "</select>";
                    });
                    $("#series").html(html);
                }
            });
        });
    </script>
} *@

MvcCorePersonajesSeries/Views/Series/Detalles.cshtml
@model MvcCorePersonajesSeries.Models.Personaje

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <h4>Personaje</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPersonaje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPersonaje)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Serie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Serie)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MvcCorePersonajesSeries/Views/Series/Index.cshtml
@model IEnumerable<MvcCorePersonajesSeries.Models.Personaje>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="Series" asp-action="Create">Crear nuevo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPersonaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Serie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPersonaje)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    <img src="@item.Imagen" alt="@item.Nombre" width="100" height="100" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Serie)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Detalles", "Detalles", new { id = item.IdPersonaje }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

MvcCorePersonajesSeries/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCorePersonajesSeries</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCorePersonajesSeries.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCorePersonajesSeries</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Series" asp-action="Index">Series</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcCorePersonajesSeries - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>